### ISSUE TITLE
Any methods to help download and preprocess EEG datasets?

### ISSUE THREAD

**Issue by xuxiran** [wjq-learning/SleepDG#2]
What an outstanding job! However, are there any methods to help download and preprocess EEG datasets? In other words, how should I obtain and preprocess these datasets?

**Comment by wjq-learning** [comment]
Thank you! The websites of datasets are shown in README.md.
And the preprocessing methods is introduced in the paper.

**Comment by xuxiran** [comment]
Thank you very much for your timely reply! However, If the pre-processing code is missing, there may be some issues with reproducibility. For example, we may not be clear on the form of pre-processing used on the data in the paper, and directly working with these five datasets can pose some difficulties for those unfamiliar with the task. Given the excellence of this work, providing the pre-processing code may enable more people (including ourselves) to reproduce and follow it. Of course, this is just my personal opinion, and I would like to express my heartfelt gratitude for your outstanding work.

**Comment by wjq-learning** [comment]
Thank you for your suggestion! I provide the code of preprocessing in [prepare_datasets](https://github.com/wjq-learning/SleepDG/tree/main/prepare_datasets)

**Comment by xuxiran** [comment]
Thank you very much! How excellent work! How nice authors!
