### ISSUE TITLE
复现效果差

### ISSUE THREAD

**Issue by OceanAnn** [wjq-learning/SleepDG#3]
作者，您好，我在复现过程中，发现如果我只用HMC和SleepEDF数据集做实验的时候，ACC和MF1都只有56左右？不知道您是否在这种条件下进行过实验吗？这种情况是否是因为作为源数据集的数据量过少呢？

**Comment by wjq-learning** [comment]
您好，我没做过只用两个数据集互相训练测试的实验，因为我的方法本身是基于多源域泛化的。至于效果不好有可能是因为源数据集过少的原因。建议用把域对齐的loss去掉，只做睡眠分期试试看。或者用其他经典睡眠分期方法试试看

**Comment by OceanAnn** [comment]
好的，谢谢您及时的回复！
